import { img1, img5 } from "@/public/images";

export const events = [
  {
    eventId: 1,
    image: img1,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 2,
    image: img1,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 3,
    image: img1,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 4,
    image: img1,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 5,
    image: img1,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 6,
    image: img1,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 7,
    image: img1,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 8,
    image: img1,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 9,
    image: img1,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 10,
    image: img1,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
];

export const pasts = [
  {
    eventId: 11,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 12,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 13,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 14,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 15,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 16,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 17,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 18,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 19,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 20,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 21,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 22,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 23,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 24,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 25,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 26,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 27,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 28,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 29,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 30,
    image: img5,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 31,
    image: img1,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    eventId: 32,
    image: img1,
    date: "Sep 28, 2018",
    location: "Yenegoa",
    title: "Huisiton's Outreach",
    description: "Dorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
];
